### ISSUE TITLE
Coisas que não ficaram claras na spec inicial

### ISSUE THREAD

**Issue by lucasfcosta** [lucasfcosta/aps-wars#2]
1. Vai haver número máximo de pontos de vida para a muralha?
2. Vamos fazer mais de um tipo de unidade militar?
3. O jogador vai poder construir uma ou quantas unidades militares ele conseguir por turno?
4. Quando a muralha for destruída e houver dano sobressalente, ele vai direto pra vila no mesmo turno ou só no turno seguinte a vila pode tomar dano?

--------------------------------------------

Minhas opiniões:

1. Sim, porém um número alto, acho que 1,5x a vida da vila
2. Acho que não, porém o custo delas tem que ser um número como por exemplo 3, para que valha apena aguardar alguns turnos antes de fazer unidades, aumentando o grau estratégico do jogo
3. Quantas unidades conseguir por turno, senão vai acabar sobrando carne e a muralha vai sempre valer muito mais apena
4. A vila toma o dano sobressalente no mesmo turno

**Comment by lucasfcosta** [comment]
passamos

**Comment by hprandi** [comment]
Da-lhe.
