### ISSUE TITLE
TODO Reta Final

### ISSUE THREAD

**Issue by hprandi** [lucasfcosta/aps-wars#5]
>> BUGS
	- Muralha não está decrementando - OK - TESTADO

>> IMPL
	- Botões desabilitados ao abrir o jogo - OK - TESTADO
	- Desabilitar o botão iniciar partida - OK - TESTADO
	- Trocar label do nome - OK - TESTADO
	- Iniciar com quantidades de recursos preenchidas com 0 - OK - TESTADO
	- Render-se - OK TESTADO
	- Fazer verificação de vencedor -OK TESTADI
	- Desconectar quando fechar o jogo - OK -TESTADO
	- Adicionar opção de desconectar - OK - TESTADO
	- Mostrar qual jogador eu sou (eu) - OK - TESTADO
	- Pequena balanceada - OK
        - Mostrar ultima ação embaixo da logo - Code ok - TESTADO
        - Mostrar as mensagens por ultimo - OK - TESTADO
        - Implementar delay para reconstruir a muralha - OK - TESTADO
     - Vida maxima da muralha - OK - >>> TESTAR << 

>> GUI
	- Slogan do Tribal Wars - OK
	- Setar o trigger do onClose - OK -TESTADO

>> DOC
	- Gerar os diagramas OK 
	- Revisar a analise de requisitos
	- Refazer os digramas faltantes OK
        - Botar argumentos nos diagramas de sequencia OK
        - Padronizar nomes OK

>> Doc especificado por diagrama
	- Diagrama de casos de uso
		Revisar - DONE

	- Diagrama de classes
		Gerar - DONE

	- Diagrama de sequência
		Gerar - ok

		* Iniciar partida - ok
		* Atacar - ok
		* Coletar recursos - ok
		* Construir tropas - ok
		* Fortalecer muralha - gerar dnv
		* render-se - ok

        * Colocar argumentos OK
        * Revisada geral OK

	- Diagrama de máquina de estados
		Conferir o da muralha - OK
		Diagrama da Vila - OK

	- Diagrama de atividades
		Revisar todos os de atividades - OK
		Revisar todos os de método - ok

		* Jogo.calcularFortalecerMuralhaPossivel - OK
		* Jogo.calcularDano - OK
		* getStringTipoAtaque - OK
		* verificarVencedor - OK
		* Muralha.decrementarPontosDeVida - OK
		* Jogo.setEstado - OK

	- Diagrama de visão geral
		Revisar - ok

**Comment by lucasfcosta** [comment]
passamos
